<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="11" failures="11" name="org.example.pruebaUnitariaTest" time="0.071" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="java.vm.version" value="17.0.8.1+1"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin"/>
    <property name="maven.multiModuleProjectDirectory" value="D:/proyectosJAVA/PROYECTOS/testing/javaTesting"/>
    <property name="java.vm.vendor" value="Eclipse Adoptium"/>
    <property name="java.vendor.url" value="https://adoptium.net/"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=";"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="user.script" value=""/>
    <property name="user.country" value="CO"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="D:\proyectosJAVA\PROYECTOS\testing\javaTesting"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="java.runtime.version" value="17.0.8.1+1"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\ASUS\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 11"/>
    <property name="classworlds.conf" value="C:/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ASUS\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot\bin;C:\oracleXE\dbhomeXE\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Java\jdk1.8.0_202\bin;C:\maven\bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY;C:\minikube;C:\minikube;C:\ProgramData\chocolatey\bin;D:\golang\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Users\ASUS\AppData\Local\Programs\Python\Python312;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\xampp\php;C:\composer;C:\Users\ASUS\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\ASUS\AppData\Local\Programs\Python\Python39;C:\Users\ASUS\AppData\Local\Microsoft\WindowsApps;C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\bin;C:\IntelliJ IDEA Community Edition 2022.3.1\bin;C:\Users\ASUS\go\bin;D:\flutter_windows_3.19.1-stable\flutter\bin;C:\Users\ASUS\AppData\Roaming\npm;C:\Users\ASUS\AppData\Roaming\Composer\vendor\bin;."/>
    <property name="maven.conf" value="C:/maven/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="61.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="10.0"/>
    <property name="library.jansi.path" value="C:/maven/lib/jansi-native"/>
    <property name="user.home" value="C:\Users\ASUS"/>
    <property name="user.timezone" value="America/Bogota"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="java.specification.version" value="17"/>
    <property name="user.name" value="ASUS"/>
    <property name="java.class.path" value="C:/maven/boot/plexus-classworlds-2.6.0.jar"/>
    <property name="java.vm.specification.version" value="17"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean install"/>
    <property name="java.home" value="C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot"/>
    <property name="user.language" value="es"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="java.version" value="17.0.8.1"/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.vendor" value="Eclipse Adoptium"/>
    <property name="sun.stderr.encoding" value="cp850"/>
    <property name="maven.home" value="C:\maven"/>
    <property name="file.separator" value="\"/>
    <property name="java.version.date" value="2023-08-24"/>
    <property name="java.vendor.url.bug" value="https://github.com/adoptium/adoptium-support/issues"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="java.vendor.version" value="Temurin-17.0.8.1+1"/>
    <property name="sun.stdout.encoding" value="cp850"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testSumar" time="0.005">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.sumar(int, int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.sumar(int, int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testSumar(pruebaUnitariaTest.java:37)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testEsPrimo" time="0.002">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testEsPrimo(pruebaUnitariaTest.java:154)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testContarLetrasA" time="0">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.contarLetrasA(String)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.contarLetrasA(String)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testContarLetrasA(pruebaUnitariaTest.java:89)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testCheckPositivos" time="0">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.checkPositivo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.checkPositivo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testCheckPositivos(pruebaUnitariaTest.java:55)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testCheckNegativo" time="0.051">
    <failure message="Unexpected exception type thrown, expected: &lt;java.lang.IllegalArgumentException&gt; but was: &lt;java.lang.NullPointerException&gt;" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;java.lang.IllegalArgumentException&gt; but was: &lt;java.lang.NullPointerException&gt;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at org.example.pruebaUnitariaTest.testCheckNegativo(pruebaUnitariaTest.java:72)
Caused by: java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.checkPositivo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.lambda$testCheckNegativo$0(pruebaUnitariaTest.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 21 more
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testesMenorAUno" time="0.007">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testesMenorAUno(pruebaUnitariaTest.java:166)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testNoEsPrimo" time="0">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.esPrimo(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testNoEsPrimo(pruebaUnitariaTest.java:179)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testFactorial" time="0.002">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.factorial(int)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.factorial(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testFactorial(pruebaUnitariaTest.java:130)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testRevertirCadena" time="0.001">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.revertirCadena(String)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.revertirCadena(String)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testRevertirCadena(pruebaUnitariaTest.java:117)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testContieneElemento" time="0.003">
    <failure message="Cannot invoke &quot;org.example.PruebaUnitaria.contieneElemento(java.util.List, String)&quot; because &quot;this.pruebaUnitaria&quot; is null" type="java.lang.NullPointerException">java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.contieneElemento(java.util.List, String)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.testContieneElemento(pruebaUnitariaTest.java:104)
</failure>
  </testcase>
  <testcase classname="org.example.pruebaUnitariaTest" name="org.example.pruebaUnitariaTest.testFactorialMenosACero" time="0">
    <failure message="Unexpected exception type thrown, expected: &lt;java.lang.IllegalArgumentException&gt; but was: &lt;java.lang.NullPointerException&gt;" type="org.opentest4j.AssertionFailedError">org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;java.lang.IllegalArgumentException&gt; but was: &lt;java.lang.NullPointerException&gt;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at org.example.pruebaUnitariaTest.testFactorialMenosACero(pruebaUnitariaTest.java:143)
Caused by: java.lang.NullPointerException: Cannot invoke &quot;org.example.PruebaUnitaria.factorial(int)&quot; because &quot;this.pruebaUnitaria&quot; is null
	at org.example.pruebaUnitariaTest.lambda$testFactorialMenosACero$1(pruebaUnitariaTest.java:144)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 21 more
</failure>
  </testcase>
</testsuite>